#!/bin/bash
# Launch Claude Code in a specific worker worktree
# Usage: launch-worker.sh <worker_number> [--prompt "task description"] [--max-turns N]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SHARED_DIR="$REPO_ROOT/.worktree-shared"
WORKTREE_ROOT="$REPO_ROOT/.worktrees"

WORKER_NUM="${1:-}"
shift || true

if [ -z "$WORKER_NUM" ]; then
  echo "Error: worker number required"
  echo "Usage: launch-worker.sh <worker_number> [--prompt \"task\"] [--max-turns N]"
  exit 1
fi

WORKER_ID="worker-$WORKER_NUM"
WORKER_DIR="$WORKTREE_ROOT/$WORKER_ID"
PORT=$((5200 + WORKER_NUM - 1))

# Defaults
PROMPT=""
MAX_TURNS=100
AUTO_CLAIM=true

# Parse flags
while [ $# -gt 0 ]; do
  case "$1" in
    --prompt) PROMPT="$2"; shift 2 ;;
    --max-turns) MAX_TURNS="$2"; shift 2 ;;
    --no-claim) AUTO_CLAIM=false; shift ;;
    *) shift ;;
  esac
done

# ─── Pre-flight: API key check ───────────────────────────────
# Workers on GCP must use ANTHROPIC_API_KEY (not OAuth) because OAuth expires
# in ~12 hours and kills long-running sessions. Check early so the failure is
# visible before wasting time claiming a task.

_preflight_api_key() {
  local key="${ANTHROPIC_API_KEY:-}"

  # 1. Already in environment
  [ -n "$key" ] && return 0

  # 2. .worktree-shared/api-key.json
  if [ -f "$SHARED_DIR/api-key.json" ]; then
    key="$(jq -r '.api_key // empty' "$SHARED_DIR/api-key.json" 2>/dev/null || true)"
    [ -n "$key" ] && return 0
  fi

  # 3. ~/.bashrc.d/anthropic.sh
  if [ -f "$HOME/.bashrc.d/anthropic.sh" ]; then
    key="$(bash -c 'source "$HOME/.bashrc.d/anthropic.sh" 2>/dev/null; echo "${ANTHROPIC_API_KEY:-}"' 2>/dev/null || true)"
    [ -n "$key" ] && return 0
  fi

  # 4. Standard locations checked by token-refresh.sh
  for loc in "$HOME/.anthropic/api_key" "$HOME/.config/anthropic/api_key" "/tmp/donut-tokens/ANTHROPIC_API_KEY.token"; do
    if [ -f "$loc" ]; then
      key="$(cat "$loc" 2>/dev/null || true)"
      [ -n "$key" ] && return 0
    fi
  done

  return 1
}

if ! _preflight_api_key; then
  echo ""
  echo "WARNING: No ANTHROPIC_API_KEY found. Worker may fail with OAuth errors."
  echo ""
  echo "  On GCP workers, OAuth tokens expire in ~12 hours and kill long-running sessions."
  echo "  Fix: run the following from your LOCAL Mac:"
  echo ""
  echo "    bash worktree/setup-gcp-apikey.sh"
  echo ""
  echo "  Continuing anyway — if you have a valid OAuth session this may still work."
  echo ""
fi

# ─────────────────────────────────────────────────────────────

# Validate worktree exists
if [ ! -d "$WORKER_DIR" ]; then
  echo "Error: Worktree $WORKER_DIR does not exist. Run setup.sh first."
  exit 1
fi

# Auto-claim a task if no prompt given
if [ -z "$PROMPT" ] && [ "$AUTO_CLAIM" = true ]; then
  echo "No prompt given, claiming next task from queue..."
  task_json="$(bash "$SCRIPT_DIR/task-queue.sh" claim "$WORKER_ID" 2>/dev/null)" || true

  if [ -z "$task_json" ] || [ "$task_json" = "No pending tasks available" ]; then
    echo "No pending tasks. Provide a --prompt or add tasks first."
    exit 0
  fi

  task_id="$(echo "$task_json" | jq -r '.id')"
  task_title="$(echo "$task_json" | jq -r '.title')"
  task_desc="$(echo "$task_json" | jq -r '.description // empty')"
  task_files="$(echo "$task_json" | jq -r '.files // [] | join(", ")')"

  PROMPT="Task: $task_title"
  [ -n "$task_desc" ] && PROMPT="$PROMPT\n\nDescription: $task_desc"
  [ -n "$task_files" ] && PROMPT="$PROMPT\n\nRelevant files: $task_files"
  # Include comprehension context if available (generated by orchestrator)
  if [ -n "${COMPREHENSION_FILE:-}" ] && [ -f "$COMPREHENSION_FILE" ]; then
    comp_content="$(cat "$COMPREHENSION_FILE")"
    PROMPT="$PROMPT\n\n## Codebase Comprehension (pre-generated)\n\n$comp_content"
    echo "Comprehension loaded: $COMPREHENSION_FILE"
  fi

  PROMPT="$PROMPT\n\nIMPORTANT: Do NOT claim additional tasks from the task queue. Only work on this single task."
  PROMPT="$PROMPT\nWhen done, commit your changes and then run:\nbash $REPO_ROOT/worktree/task-queue.sh complete $task_id --worker $WORKER_ID --result success"

  echo "Claimed task: $task_id — $task_title"
fi

# ─── Load API key from shared config ─────────────────────────

if [ -f "$SHARED_DIR/api-key.json" ]; then
  api_key="$(jq -r '.api_key // empty' "$SHARED_DIR/api-key.json" 2>/dev/null)"
  if [ -n "$api_key" ]; then
    export ANTHROPIC_API_KEY="$api_key"
  fi
fi

# Fallback: check ~/.bashrc.d/anthropic.sh
if [ -z "${ANTHROPIC_API_KEY:-}" ] && [ -f "$HOME/.bashrc.d/anthropic.sh" ]; then
  # shellcheck disable=SC1091
  source "$HOME/.bashrc.d/anthropic.sh"
fi

# Final check — warn but don't abort (OAuth may still be valid locally)
if [ -z "${ANTHROPIC_API_KEY:-}" ]; then
  echo "WARNING: No ANTHROPIC_API_KEY found. Worker may fail with OAuth errors."
  echo "Run: bash worktree/setup-gcp-apikey.sh"
fi

# ─────────────────────────────────────────────────────────────

# Set worker environment
export WORKER_ID="$WORKER_ID"
export WORKER_NUM="$WORKER_NUM"
export WORKER_PORT="$PORT"
export MAIN_REPO="$REPO_ROOT"
export WORKTREE_SHARED_DIR="$SHARED_DIR"

echo ""
echo "=== Launching Claude Code ==="
echo "  Worker:    $WORKER_ID"
echo "  Directory: $WORKER_DIR"
echo "  Port:      $PORT"
echo "  Max turns: $MAX_TURNS"
if [ -n "${ANTHROPIC_API_KEY:-}" ]; then
  echo "  Auth:      ANTHROPIC_API_KEY (${ANTHROPIC_API_KEY:0:16}...)"
else
  echo "  Auth:      OAuth (session-based — expires in ~12h)"
fi
echo ""

# Create session log directory
SESSION_DIR="$WORKER_DIR/data"
mkdir -p "$SESSION_DIR"
SESSION_FILE="$SESSION_DIR/session-$(date +%s).json"

# Launch Claude Code
cd "$WORKER_DIR"

if [ -n "$PROMPT" ]; then
  claude \
    --dangerously-skip-permissions \
    --output-format stream-json --verbose \
    -p "$(echo -e "$PROMPT")" \
    2>&1 | tee "$SESSION_FILE"
  EXIT_CODE=${PIPESTATUS[0]}
else
  # Interactive mode
  claude \
    --dangerously-skip-permissions
  EXIT_CODE=$?
fi

echo ""
echo "=== Worker $WORKER_ID finished (exit: $EXIT_CODE) ==="
[ -f "$SESSION_FILE" ] && echo "Session saved: $SESSION_FILE"
