#!/bin/bash
# Launch Claude Code in a specific worker worktree
# Usage: launch-worker.sh <worker_number> [--prompt "task description"] [--max-turns N]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SHARED_DIR="$REPO_ROOT/.worktree-shared"
WORKTREE_ROOT="$REPO_ROOT/.worktrees"

WORKER_NUM="${1:-}"
shift || true

if [ -z "$WORKER_NUM" ]; then
  echo "Error: worker number required"
  echo "Usage: launch-worker.sh <worker_number> [--prompt \"task\"] [--max-turns N]"
  exit 1
fi

WORKER_ID="worker-$WORKER_NUM"
WORKER_DIR="$WORKTREE_ROOT/$WORKER_ID"
PORT=$((5200 + WORKER_NUM - 1))

# Defaults
PROMPT=""
MAX_TURNS=100
AUTO_CLAIM=true

# Parse flags
while [ $# -gt 0 ]; do
  case "$1" in
    --prompt) PROMPT="$2"; shift 2 ;;
    --max-turns) MAX_TURNS="$2"; shift 2 ;;
    --no-claim) AUTO_CLAIM=false; shift ;;
    *) shift ;;
  esac
done

# ─── Pre-flight: API key check ───────────────────────────────
# Workers on GCP must use ANTHROPIC_API_KEY (not OAuth) because OAuth expires
# in ~12 hours and kills long-running sessions. Check early so the failure is
# visible before wasting time claiming a task.

_preflight_api_key() {
  local key="${ANTHROPIC_API_KEY:-}"

  # 1. Already in environment
  [ -n "$key" ] && return 0

  # 2. .worktree-shared/api-key.json
  if [ -f "$SHARED_DIR/api-key.json" ]; then
    key="$(jq -r '.api_key // empty' "$SHARED_DIR/api-key.json" 2>/dev/null || true)"
    [ -n "$key" ] && return 0
  fi

  # 3. ~/.bashrc.d/anthropic.sh
  if [ -f "$HOME/.bashrc.d/anthropic.sh" ]; then
    key="$(bash -c 'source "$HOME/.bashrc.d/anthropic.sh" 2>/dev/null; echo "${ANTHROPIC_API_KEY:-}"' 2>/dev/null || true)"
    [ -n "$key" ] && return 0
  fi

  # 4. Standard locations checked by token-refresh.sh
  for loc in "$HOME/.anthropic/api_key" "$HOME/.config/anthropic/api_key" "/tmp/donut-tokens/ANTHROPIC_API_KEY.token"; do
    if [ -f "$loc" ]; then
      key="$(cat "$loc" 2>/dev/null || true)"
      [ -n "$key" ] && return 0
    fi
  done

  return 1
}

if ! _preflight_api_key; then
  echo ""
  echo "WARNING: No ANTHROPIC_API_KEY found. Worker may fail with OAuth errors."
  echo ""
  echo "  On GCP workers, OAuth tokens expire in ~12 hours and kill long-running sessions."
  echo "  Fix: run the following from your LOCAL Mac:"
  echo ""
  echo "    bash worktree/setup-gcp-apikey.sh"
  echo ""
  echo "  Continuing anyway — if you have a valid OAuth session this may still work."
  echo ""
fi

# ─────────────────────────────────────────────────────────────

# Validate worktree exists
if [ ! -d "$WORKER_DIR" ]; then
  echo "Error: Worktree $WORKER_DIR does not exist. Run setup.sh first."
  exit 1
fi

# Auto-claim a task if no prompt given
if [ -z "$PROMPT" ] && [ "$AUTO_CLAIM" = true ]; then
  echo "No prompt given, claiming next task from queue..."
  task_json="$(bash "$SCRIPT_DIR/task-queue.sh" claim "$WORKER_ID" 2>/dev/null)" || true

  if [ -z "$task_json" ] || [ "$task_json" = "No pending tasks available" ]; then
    echo "No pending tasks. Provide a --prompt or add tasks first."
    exit 0
  fi

  task_id="$(echo "$task_json" | jq -r '.id')"
  task_title="$(echo "$task_json" | jq -r '.title')"
  task_desc="$(echo "$task_json" | jq -r '.description // empty')"
  task_files="$(echo "$task_json" | jq -r '.files // [] | join(", ")')"

  PROMPT="Task: $task_title"
  [ -n "$task_desc" ] && PROMPT="$PROMPT\n\nDescription: $task_desc"
  [ -n "$task_files" ] && PROMPT="$PROMPT\n\nRelevant files: $task_files"
  # Include comprehension context if available (generated by orchestrator)
  if [ -n "${COMPREHENSION_FILE:-}" ] && [ -f "$COMPREHENSION_FILE" ]; then
    comp_content="$(cat "$COMPREHENSION_FILE")"
    PROMPT="$PROMPT\n\n## Codebase Comprehension (pre-generated)\n\n$comp_content"
    echo "Comprehension loaded: $COMPREHENSION_FILE"
  fi

  PROMPT="$PROMPT\n\nIMPORTANT: Do NOT claim additional tasks from the task queue. Only work on this single task."
  PROMPT="$PROMPT\nWhen done, commit your changes and then run:\nbash $REPO_ROOT/worktree/task-queue.sh complete $task_id --worker $WORKER_ID --result success"

  echo "Claimed task: $task_id — $task_title"
fi

# ─── Load API key from shared config ─────────────────────────

if [ -f "$SHARED_DIR/api-key.json" ]; then
  api_key="$(jq -r '.api_key // empty' "$SHARED_DIR/api-key.json" 2>/dev/null)"
  if [ -n "$api_key" ]; then
    export ANTHROPIC_API_KEY="$api_key"
  fi
fi

# Fallback: check ~/.bashrc.d/anthropic.sh
if [ -z "${ANTHROPIC_API_KEY:-}" ] && [ -f "$HOME/.bashrc.d/anthropic.sh" ]; then
  # shellcheck disable=SC1091
  source "$HOME/.bashrc.d/anthropic.sh"
fi

# Final check — warn but don't abort (OAuth may still be valid locally)
if [ -z "${ANTHROPIC_API_KEY:-}" ]; then
  echo "WARNING: No ANTHROPIC_API_KEY found. Worker may fail with OAuth errors."
  echo "Run: bash worktree/setup-gcp-apikey.sh"
fi

# ─────────────────────────────────────────────────────────────

# ─── Skills dir injection (pattern from Paperclip) ──────────
# Build a temp directory with .claude/skills/ containing symlinks to core
# skills, then pass via --add-dir so Claude discovers them natively.
# This closes Gap 1 (Skill Asymmetry: 27 skills → 0 skills).

SKILLS_DIR=""
_build_skills_dir() {
  local tmp
  tmp="$(mktemp -d "${TMPDIR:-/tmp}/worker-skills-XXXXXX")"
  local target="$tmp/.claude/skills"
  mkdir -p "$target"

  # Source 1: repo-local skills (if worktree project has .claude/skills/)
  if [ -d "$WORKER_DIR/.claude/skills" ]; then
    for skill in "$WORKER_DIR/.claude/skills"/*/; do
      [ -d "$skill" ] || continue
      local name
      name="$(basename "$skill")"
      ln -sf "$skill" "$target/$name" 2>/dev/null || true
    done
  fi

  # Source 2: user's global skills (~/.claude/skills/)
  local global_skills="$HOME/.claude/skills"
  if [ -d "$global_skills" ]; then
    for skill in "$global_skills"/*/; do
      [ -d "$skill" ] || continue
      local name
      name="$(basename "$skill")"
      # Don't override repo-local skills
      [ -L "$target/$name" ] || [ -d "$target/$name" ] && continue
      ln -sf "$skill" "$target/$name" 2>/dev/null || true
    done
  fi

  # Count injected skills
  local count=0
  [ -d "$target" ] && count="$(find "$target" -maxdepth 1 -mindepth 1 -type l 2>/dev/null | wc -l | tr -d ' ')"

  if [ "$count" -gt 0 ]; then
    SKILLS_DIR="$tmp"
    echo "Skills injected: $count skills via --add-dir"
  else
    rm -rf "$tmp"
  fi
}

_build_skills_dir

# ─── Session resume (pattern from Paperclip) ────────────────
# If a previous session exists for this task, resume it instead of starting
# fresh. This closes Gap 2 (Context Disparity: 6 files → 0).

RESUME_SESSION_ID=""
if [ -n "${task_id:-}" ]; then
  SESSION_STORE="$SHARED_DIR/sessions"
  if [ -f "$SESSION_STORE/${task_id}.session" ]; then
    RESUME_SESSION_ID="$(cat "$SESSION_STORE/${task_id}.session" 2>/dev/null || true)"
    if [ -n "$RESUME_SESSION_ID" ]; then
      echo "Resuming session: $RESUME_SESSION_ID (from previous run of $task_id)"
    fi
  fi
fi

# ─────────────────────────────────────────────────────────────

# Set worker environment
export WORKER_ID="$WORKER_ID"
export WORKER_NUM="$WORKER_NUM"
export WORKER_PORT="$PORT"
export MAIN_REPO="$REPO_ROOT"
export WORKTREE_SHARED_DIR="$SHARED_DIR"

echo ""
echo "=== Launching Claude Code ==="
echo "  Worker:    $WORKER_ID"
echo "  Directory: $WORKER_DIR"
echo "  Port:      $PORT"
echo "  Max turns: $MAX_TURNS"
[ -n "$SKILLS_DIR" ] && echo "  Skills:    $SKILLS_DIR"
[ -n "$RESUME_SESSION_ID" ] && echo "  Resume:    $RESUME_SESSION_ID"
if [ -n "${ANTHROPIC_API_KEY:-}" ]; then
  echo "  Auth:      ANTHROPIC_API_KEY (${ANTHROPIC_API_KEY:0:16}...)"
else
  echo "  Auth:      OAuth (session-based — expires in ~12h)"
fi
echo ""

# Create session log directory
SESSION_DIR="$WORKER_DIR/data"
mkdir -p "$SESSION_DIR"
SESSION_FILE="$SESSION_DIR/session-$(date +%s).json"

# Build extra CLI args for skills and session resume
EXTRA_ARGS=()
[ -n "$SKILLS_DIR" ] && EXTRA_ARGS+=(--add-dir "$SKILLS_DIR")
[ -n "$RESUME_SESSION_ID" ] && EXTRA_ARGS+=(--resume "$RESUME_SESSION_ID")

# Launch Claude Code
cd "$WORKER_DIR"

if [ -n "$PROMPT" ]; then
  claude \
    --dangerously-skip-permissions \
    --output-format stream-json --verbose \
    --max-turns "$MAX_TURNS" \
    "${EXTRA_ARGS[@]}" \
    -p "$(echo -e "$PROMPT")" \
    2>&1 | tee "$SESSION_FILE"
  EXIT_CODE=${PIPESTATUS[0]}
else
  # Interactive mode (no stream-json, no resume, no skills)
  claude \
    --dangerously-skip-permissions
  EXIT_CODE=$?
fi

echo ""
echo "=== Worker $WORKER_ID finished (exit: $EXIT_CODE) ==="

# ─── Post-run: parse session for cost + session persistence ──
# Pattern from Paperclip: extract cost/usage/session_id from stream-json
# output, save for cost tracking and future session resume.

if [ -f "$SESSION_FILE" ] && [ -s "$SESSION_FILE" ]; then
  echo "Session saved: $SESSION_FILE"

  PARSE_ARGS=(
    "$SESSION_FILE"
    --save-cost "$SHARED_DIR/costs"
    --save-session "$SHARED_DIR/sessions"
  )
  [ -n "${task_id:-}" ] && PARSE_ARGS+=(--task-id "$task_id")
  PARSE_ARGS+=(--worker-id "$WORKER_ID")

  PARSED="$(bash "$SCRIPT_DIR/parse-session.sh" "${PARSE_ARGS[@]}" 2>/dev/null)" || true

  if [ -n "$PARSED" ]; then
    cost="$(echo "$PARSED" | jq -r '.cost_usd // 0')"
    in_tok="$(echo "$PARSED" | jq -r '.usage.input_tokens // 0')"
    out_tok="$(echo "$PARSED" | jq -r '.usage.output_tokens // 0')"
    cached="$(echo "$PARSED" | jq -r '.usage.cached_tokens // 0')"
    sid="$(echo "$PARSED" | jq -r '.session_id // empty')"
    echo ""
    echo "  Cost:    \$$cost"
    echo "  Tokens:  ${in_tok} in (${cached} cached) / ${out_tok} out"
    [ -n "$sid" ] && echo "  Session: $sid (saved for resume)"
  fi
fi

# Clean up temp skills dir
[ -n "$SKILLS_DIR" ] && rm -rf "$SKILLS_DIR" 2>/dev/null || true
