#!/bin/bash
# Quality Ratchet — Re-scan gate results, generate improvement tasks for marginal work.
# Pure bash + jq. No AI. Runs periodically (daily default).
#
# Usage:
#   quality-ratchet.sh [--days N] [--threshold N] [--dry-run]
#
# Scans .worktree-shared/gate-results/*.json for tasks that:
#   - PASSED the gate but with marginal scores (tier2 overall 7-8)
#   - Have individual dimension scores <= 6
#   - Have skill linter warnings > 3
# Generates "improve: <title>" tasks at low priority.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SHARED_DIR="${WORKTREE_SHARED_DIR:-$REPO_ROOT/.worktree-shared}"
GATE_DIR="$SHARED_DIR/gate-results"
TASKS_FILE="$SHARED_DIR/dev-tasks.json"

# Defaults
LOOKBACK_DAYS=7
THRESHOLD=9  # scores >= this are fine; below this get flagged (so 7-8 get flagged)
DRY_RUN=false
GENERATED=0

# Parse flags
while [ $# -gt 0 ]; do
  case "$1" in
    --days) LOOKBACK_DAYS="$2"; shift 2 ;;
    --threshold) THRESHOLD="$2"; shift 2 ;;
    --dry-run) DRY_RUN=true; shift ;;
    *) echo "Unknown flag: $1"; exit 1 ;;
  esac
done

if [ ! -d "$GATE_DIR" ]; then
  echo "No gate-results directory found at $GATE_DIR"
  exit 0
fi

# Calculate cutoff timestamp
if command -v gdate &>/dev/null; then
  CUTOFF=$(gdate -d "-${LOOKBACK_DAYS} days" +%s 2>/dev/null || date -v-${LOOKBACK_DAYS}d +%s)
else
  CUTOFF=$(date -v-${LOOKBACK_DAYS}d +%s 2>/dev/null || date -d "-${LOOKBACK_DAYS} days" +%s)
fi

# Check if an improvement task already exists for a given title
task_exists() {
  local title="$1"
  if [ -f "$TASKS_FILE" ]; then
    local count
    count=$(jq --arg t "$title" '[.tasks[] | select(.title == $t)] | length' "$TASKS_FILE" 2>/dev/null || echo "0")
    [ "$count" -gt 0 ]
  else
    return 1
  fi
}

echo "Quality Ratchet: scanning gate results (last ${LOOKBACK_DAYS} days, threshold ${THRESHOLD})"
echo "Gate dir: $GATE_DIR"
echo ""

for result_file in "$GATE_DIR"/*.json; do
  [ -f "$result_file" ] || continue

  # Check file age
  file_mtime=$(stat -f %m "$result_file" 2>/dev/null || stat -c %Y "$result_file" 2>/dev/null || echo "0")
  if [ "$file_mtime" -lt "$CUTOFF" ]; then
    continue
  fi

  # Read gate result
  passed=$(jq -r '.pass // false' "$result_file" 2>/dev/null || echo "false")
  if [ "$passed" != "true" ]; then
    continue  # only re-assess passed tasks
  fi

  task_id=$(jq -r '.task_id // "unknown"' "$result_file" 2>/dev/null || echo "unknown")
  task_title=$(jq -r '.task_title // "unknown"' "$result_file" 2>/dev/null || echo "unknown")

  # Check tier2 scores
  tier2_overall=$(jq -r '.tier2.overall // 10' "$result_file" 2>/dev/null || echo "10")
  tier2_pass=$(jq -r '.tier2.pass // true' "$result_file" 2>/dev/null || echo "true")

  # Find low individual dimensions
  low_dims=""
  for dim in correctness readability convention security completeness simplicity; do
    score=$(jq -r ".tier2.scores.${dim} // 10" "$result_file" 2>/dev/null || echo "10")
    if [ "$score" -le 6 ] 2>/dev/null; then
      low_dims="${low_dims}${dim}(${score}) "
    fi
  done

  # Check skill linter warnings
  linter_warnings=$(jq -r '.tier1.skill_linter.warnings // 0' "$result_file" 2>/dev/null || echo "0")

  # Determine if this task is marginal
  is_marginal=false
  reasons=""

  if [ "$tier2_overall" -lt "$THRESHOLD" ] 2>/dev/null && [ "$tier2_overall" -ge 7 ] 2>/dev/null; then
    is_marginal=true
    reasons="${reasons}Overall score ${tier2_overall}/10 (marginal). "
  fi

  if [ -n "$low_dims" ]; then
    is_marginal=true
    reasons="${reasons}Low dimensions: ${low_dims}. "
  fi

  if [ "$linter_warnings" -gt 3 ] 2>/dev/null; then
    is_marginal=true
    reasons="${reasons}Skill linter: ${linter_warnings} warnings. "
  fi

  if [ "$is_marginal" = "false" ]; then
    continue
  fi

  # Build improvement task
  improve_title="improve: ${task_title}"

  # Dedup check
  if task_exists "$improve_title"; then
    echo "  SKIP (exists): $improve_title"
    continue
  fi

  description="IMPROVEMENT TASK (auto-generated by quality ratchet)

Original task: ${task_title} (${task_id})
Gate result: ${result_file}

Issues to address:
${reasons}

Review the original implementation and improve the areas identified above.
Focus on quality improvements, not new features."

  if [ "$DRY_RUN" = "true" ]; then
    echo "  WOULD CREATE: $improve_title"
    echo "    Reasons: $reasons"
  else
    bash "$SCRIPT_DIR/task-queue.sh" add "$improve_title" \
      --priority low \
      --description "$description" \
      --parent-task "$task_id"
    echo "  CREATED: $improve_title"
  fi

  GENERATED=$((GENERATED + 1))
done

echo ""
echo "Quality Ratchet complete: ${GENERATED} improvement tasks ${DRY_RUN:+would be }generated"
