#!/bin/bash
# Refresh ANTHROPIC_API_KEY on GCP claude-code-server (cron/launchd safe)
# Run LOCALLY (from your Mac). Safe to run multiple times.
#
# Usage:
#   bash scripts/worktree/refresh-gcp-apikey.sh
#
# Add to macOS launchd alongside token-refresh.sh for periodic sync:
#   Suggested interval: every 6 hours (matches session lifetime)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

LOG_FILE="${LOG_FILE:-/tmp/donut-refresh-gcp-apikey.log}"

GCP_ZONE="${GCP_ZONE:-us-central1-a}"
GCP_INSTANCE="${GCP_INSTANCE:-claude-code-server}"
REMOTE_WORKSPACE="$HOME/claude-workspace/donut-dev"
REMOTE_SHARED_DIR="$REMOTE_WORKSPACE/.worktree-shared"
REMOTE_BASHRC_DIR="$HOME/.bashrc.d"

# ─── Logging ─────────────────────────────────────────────────

log() {
  local level="$1"; shift
  local msg="[$(date -u +%Y-%m-%dT%H:%M:%SZ)] [refresh-gcp-apikey] [$level] $*"
  echo "$msg"
  echo "$msg" >> "$LOG_FILE" 2>/dev/null || true
}

# ─── Resolve API key ─────────────────────────────────────────

API_KEY="${ANTHROPIC_API_KEY:-}"

if [ -z "$API_KEY" ]; then
  for loc in "$HOME/.anthropic/api_key" "$HOME/.config/anthropic/api_key" "/tmp/donut-tokens/ANTHROPIC_API_KEY.token"; do
    if [ -f "$loc" ]; then
      API_KEY="$(cat "$loc" 2>/dev/null || true)"
      [ -n "$API_KEY" ] && break
    fi
  done
fi

if [ -z "$API_KEY" ]; then
  log "ERROR" "No ANTHROPIC_API_KEY found in environment or standard locations."
  log "ERROR" "Set ANTHROPIC_API_KEY before running this script, or run setup-gcp-apikey.sh for interactive setup."
  exit 1
fi

if [[ "$API_KEY" != sk-ant-* ]]; then
  log "WARN" "Key does not start with 'sk-ant-' — verify it is correct."
fi

# ─── Require gcloud ──────────────────────────────────────────

if ! command -v gcloud &>/dev/null; then
  log "ERROR" "gcloud not found. Cannot SSH to GCP VM."
  exit 1
fi

log "INFO" "Refreshing API key on $GCP_INSTANCE (zone: $GCP_ZONE)..."

# ─── Update api-key.json ─────────────────────────────────────

gcloud compute ssh "$GCP_INSTANCE" \
  --zone="$GCP_ZONE" \
  --tunnel-through-iap \
  --quiet \
  --command="
    set -e
    mkdir -p '$REMOTE_SHARED_DIR'
    printf '{\"api_key\":\"%s\",\"updated_at\":\"%s\"}\n' \
      '$API_KEY' \
      \"\$(date -u +%Y-%m-%dT%H:%M:%SZ)\" \
      > '$REMOTE_SHARED_DIR/api-key.json'
    chmod 600 '$REMOTE_SHARED_DIR/api-key.json'
  " 2>/dev/null

# ─── Update .bashrc.d/anthropic.sh ───────────────────────────

gcloud compute ssh "$GCP_INSTANCE" \
  --zone="$GCP_ZONE" \
  --tunnel-through-iap \
  --quiet \
  --command="
    set -e
    mkdir -p '$REMOTE_BASHRC_DIR'
    cat > '$REMOTE_BASHRC_DIR/anthropic.sh' << 'REMOTE_EOF'
# Auto-generated by refresh-gcp-apikey.sh — do not edit manually
# Updated: $(date -u +%Y-%m-%dT%H:%M:%SZ)
export ANTHROPIC_API_KEY='$API_KEY'
REMOTE_EOF
    chmod 600 '$REMOTE_BASHRC_DIR/anthropic.sh'
  " 2>/dev/null

log "INFO" "API key refreshed on $GCP_INSTANCE (key: ${API_KEY:0:16}...)"
log "INFO" "Log: $LOG_FILE"
