#!/bin/bash
# One-time setup: inject ANTHROPIC_API_KEY into GCP claude-code-server
# Run LOCALLY (from your Mac) to configure the GCP VM for OAuth-free worker execution.
#
# Usage:
#   bash scripts/worktree/setup-gcp-apikey.sh
#   ANTHROPIC_API_KEY=sk-ant-... bash scripts/worktree/setup-gcp-apikey.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

GCP_ZONE="${GCP_ZONE:-us-central1-a}"
GCP_INSTANCE="${GCP_INSTANCE:-claude-code-server}"
REMOTE_WORKSPACE="$HOME/claude-workspace/donut-dev"
REMOTE_SHARED_DIR="$REMOTE_WORKSPACE/.worktree-shared"
REMOTE_BASHRC_DIR="$HOME/.bashrc.d"

# ─── Resolve API key ─────────────────────────────────────────

API_KEY="${ANTHROPIC_API_KEY:-}"

if [ -z "$API_KEY" ]; then
  # Try common local locations (mirrors token-refresh.sh logic)
  for loc in "$HOME/.anthropic/api_key" "$HOME/.config/anthropic/api_key" "/tmp/donut-tokens/ANTHROPIC_API_KEY.token"; do
    if [ -f "$loc" ]; then
      API_KEY="$(cat "$loc" 2>/dev/null || true)"
      [ -n "$API_KEY" ] && break
    fi
  done
fi

if [ -z "$API_KEY" ]; then
  echo ""
  echo "No ANTHROPIC_API_KEY found in environment or standard locations."
  echo ""
  printf "Enter your Anthropic API key (sk-ant-...): "
  read -rs API_KEY
  echo ""
fi

if [ -z "$API_KEY" ]; then
  echo "ERROR: API key is required." >&2
  exit 1
fi

if [[ "$API_KEY" != sk-ant-* ]]; then
  echo "WARNING: Key does not start with 'sk-ant-' — double-check it is an Anthropic key."
fi

# ─── Verify gcloud is available ──────────────────────────────

if ! command -v gcloud &>/dev/null; then
  echo "ERROR: gcloud not found. Install the Google Cloud SDK first." >&2
  exit 1
fi

GCP_PROJECT="$(gcloud config get-value project 2>/dev/null || true)"
echo ""
echo "=== GCP API Key Setup ==="
echo "  Instance: $GCP_INSTANCE"
echo "  Zone:     $GCP_ZONE"
echo "  Project:  ${GCP_PROJECT:-<default>}"
echo "  Key:      ${API_KEY:0:16}..."
echo ""

# ─── Write api-key.json to .worktree-shared/ ─────────────────

echo "Step 1/2: Writing .worktree-shared/api-key.json on GCP VM..."

gcloud compute ssh "$GCP_INSTANCE" \
  --zone="$GCP_ZONE" \
  --tunnel-through-iap \
  --command="
    set -e
    mkdir -p '$REMOTE_SHARED_DIR'
    # Write with restricted permissions (owner read-only)
    printf '{\"api_key\":\"%s\",\"updated_at\":\"%s\"}\\n' \
      '$API_KEY' \
      \"\$(date -u +%Y-%m-%dT%H:%M:%SZ)\" \
      > '$REMOTE_SHARED_DIR/api-key.json'
    chmod 600 '$REMOTE_SHARED_DIR/api-key.json'
    echo 'Written: $REMOTE_SHARED_DIR/api-key.json'
  "

echo ""
echo "Step 2/2: Writing ~/.bashrc.d/anthropic.sh on GCP VM..."

gcloud compute ssh "$GCP_INSTANCE" \
  --zone="$GCP_ZONE" \
  --tunnel-through-iap \
  --command="
    set -e
    mkdir -p '$REMOTE_BASHRC_DIR'
    cat > '$REMOTE_BASHRC_DIR/anthropic.sh' << 'REMOTE_EOF'
# Auto-generated by setup-gcp-apikey.sh — do not edit manually
# Updated: $(date -u +%Y-%m-%dT%H:%M:%SZ)
export ANTHROPIC_API_KEY='$API_KEY'
REMOTE_EOF
    chmod 600 '$REMOTE_BASHRC_DIR/anthropic.sh'
    # Ensure .bashrc sources .bashrc.d/ files
    if ! grep -q 'bashrc.d' ~/.bashrc 2>/dev/null; then
      cat >> ~/.bashrc << 'BASHRC_EOF'

# Source any additional env files from ~/.bashrc.d/
if [ -d \"\$HOME/.bashrc.d\" ]; then
  for f in \"\$HOME/.bashrc.d/\"*.sh; do
    [ -r \"\$f\" ] && source \"\$f\"
  done
fi
BASHRC_EOF
      echo 'Added .bashrc.d sourcing block to ~/.bashrc'
    fi
    echo 'Written: $REMOTE_BASHRC_DIR/anthropic.sh'
  "

echo ""
echo "=== Verification ==="

gcloud compute ssh "$GCP_INSTANCE" \
  --zone="$GCP_ZONE" \
  --tunnel-through-iap \
  --command="
    echo -n 'api-key.json: '
    if [ -f '$REMOTE_SHARED_DIR/api-key.json' ]; then
      python3 -c \"import json; d=json.load(open('$REMOTE_SHARED_DIR/api-key.json')); print('OK — key=' + d['api_key'][:16] + '...')\"
    else
      echo 'MISSING'
    fi

    echo -n 'anthropic.sh: '
    if [ -f '$REMOTE_BASHRC_DIR/anthropic.sh' ]; then
      echo 'OK'
    else
      echo 'MISSING'
    fi
  "

echo ""
echo "API key injected. Workers on $GCP_INSTANCE will use ANTHROPIC_API_KEY instead of OAuth."
echo ""
echo "Next steps:"
echo "  - Run workers as normal: bash scripts/worktree/launch-worker.sh <N>"
echo "  - To refresh the key later: bash scripts/worktree/refresh-gcp-apikey.sh"
echo "  - To add periodic refresh (recommended): add refresh-gcp-apikey.sh to macOS launchd"
