#!/bin/bash
# Donut Workflow Automation Installer
# One command to set up all automations. Run once, never think about it again.
# Usage: bash scripts/automation/install.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
GIT_ROOT="$(git -C "$REPO_ROOT" rev-parse --show-toplevel 2>/dev/null || echo "$REPO_ROOT")"
GIT_DIR="$(git -C "$REPO_ROOT" rev-parse --git-dir 2>/dev/null)"
HOOKS_DIR="$GIT_DIR/hooks"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

ok() { echo -e "  ${GREEN}[OK]${NC} $1"; }
skip() { echo -e "  ${YELLOW}[SKIP]${NC} $1"; }
info() { echo "  [INFO] $1"; }

echo "═══════════════════════════════════════════════"
echo "  Donut Workflow Automation Installer"
echo "═══════════════════════════════════════════════"
echo ""

# ─── 1. Git Hooks ───────────────────────────────────────────

echo "1. Git Hooks"

mkdir -p "$HOOKS_DIR"

# Pre-push hook: auto-runs deploy-check before any push
PREPUSH="$HOOKS_DIR/pre-push"
if [ -f "$PREPUSH" ] && ! grep -q "donut-deploy-check" "$PREPUSH" 2>/dev/null; then
  # Append to existing hook
  cat >> "$PREPUSH" << 'HOOK'

# --- donut-deploy-check ---
DONUT_DIR="$HOME/Desktop/Donut/Personal/claude-infra"
if [ -f "$DONUT_DIR/automation/deploy-check.sh" ]; then
  echo "[donut] Running pre-push validation..."
  if ! bash "$DONUT_DIR/automation/deploy-check.sh" --skip-build 2>&1; then
    echo "[donut] Pre-push check failed. Push blocked."
    echo "[donut] Run 'bash Personal/claude-infra/automation/deploy-check.sh --fix' to auto-fix."
    exit 1
  fi
fi
# --- end donut-deploy-check ---
HOOK
  chmod +x "$PREPUSH"
  ok "Appended deploy-check to existing pre-push hook"
else
  cat > "$PREPUSH" << 'HOOK'
#!/bin/bash
# Auto-generated by Donut automation installer

# --- donut-deploy-check ---
DONUT_DIR="$HOME/Desktop/Donut/Personal/claude-infra"
if [ -f "$DONUT_DIR/automation/deploy-check.sh" ]; then
  echo "[donut] Running pre-push validation..."
  if ! bash "$DONUT_DIR/automation/deploy-check.sh" --skip-build 2>&1; then
    echo "[donut] Pre-push check failed. Push blocked."
    echo "[donut] Run 'bash Personal/claude-infra/automation/deploy-check.sh --fix' to auto-fix."
    exit 1
  fi
fi
# --- end donut-deploy-check ---
HOOK
  chmod +x "$PREPUSH"
  ok "Installed pre-push hook (deploy-check)"
fi

# Post-commit hook: auto-runs session-handoff after each commit
POSTCOMMIT="$HOOKS_DIR/post-commit"
if [ -f "$POSTCOMMIT" ] && ! grep -q "donut-session-handoff" "$POSTCOMMIT" 2>/dev/null; then
  cat >> "$POSTCOMMIT" << 'HOOK'

# --- donut-session-handoff ---
DONUT_DIR="$HOME/Desktop/Donut/Personal/claude-infra"
if [ -f "$DONUT_DIR/automation/session-handoff.sh" ]; then
  COMMIT_MSG=$(git log -1 --pretty=%s 2>/dev/null || echo "")
  bash "$DONUT_DIR/automation/session-handoff.sh" --message "$COMMIT_MSG" >/dev/null 2>&1 &
fi
# --- end donut-session-handoff ---
HOOK
  chmod +x "$POSTCOMMIT"
  ok "Appended session-handoff to existing post-commit hook"
else
  cat > "$POSTCOMMIT" << 'HOOK'
#!/bin/bash
# Auto-generated by Donut automation installer

# --- donut-session-handoff ---
DONUT_DIR="$HOME/Desktop/Donut/Personal/claude-infra"
if [ -f "$DONUT_DIR/automation/session-handoff.sh" ]; then
  COMMIT_MSG=$(git log -1 --pretty=%s 2>/dev/null || echo "")
  bash "$DONUT_DIR/automation/session-handoff.sh" --message "$COMMIT_MSG" >/dev/null 2>&1 &
fi
# --- end donut-session-handoff ---
HOOK
  chmod +x "$POSTCOMMIT"
  ok "Installed post-commit hook (session-handoff)"
fi

echo ""

# ─── 2. Token Refresh launchd ──────────────────────────────

echo "2. Token Refresh (macOS launchd)"

LAUNCH_AGENTS="$HOME/Library/LaunchAgents"
PLIST_NAME="com.donut.token-refresh.plist"
PLIST_SRC="$SCRIPT_DIR/com.donut.token-refresh.plist"
PLIST_DST="$LAUNCH_AGENTS/$PLIST_NAME"

mkdir -p "$LAUNCH_AGENTS"

# Copy script to ~/.local/bin (macOS launchd can't access ~/Desktop sandbox)
WRAPPER="$HOME/.local/bin/donut-token-refresh"
mkdir -p "$(dirname "$WRAPPER")"
cp "$SCRIPT_DIR/token-refresh.sh" "$WRAPPER"
chmod +x "$WRAPPER"
info "Installed: $WRAPPER"

# Generate plist with wrapper path (no spaces)
cat > "$PLIST_DST" << PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.donut.token-refresh</string>
    <key>ProgramArguments</key>
    <array>
        <string>$WRAPPER</string>
        <string>--check</string>
    </array>
    <key>StartInterval</key>
    <integer>900</integer>
    <key>RunAtLoad</key>
    <true/>
    <key>StandardOutPath</key>
    <string>/tmp/donut-token-refresh.log</string>
    <key>StandardErrorPath</key>
    <string>/tmp/donut-token-refresh.log</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>/usr/local/bin:/usr/bin:/bin:/opt/homebrew/bin:$HOME/.bun/bin:$HOME/.local/bin</string>
        <key>HOME</key>
        <string>$HOME</string>
    </dict>
</dict>
</plist>
PLIST

# Unload if already loaded, then reload
launchctl unload "$PLIST_DST" 2>/dev/null || true
launchctl load "$PLIST_DST" 2>/dev/null && ok "Token refresh daemon installed (every 15min)" || skip "launchctl load failed (may need reboot)"

# ─── 2b. Morning Brief Hook ────────────────────────────────

# Install Claude Code UserPromptSubmit hook script
HOOK_BIN="$HOME/.local/bin/donut-morning-hook"
cat > "$HOOK_BIN" << 'HOOKEOF'
#!/bin/bash
# Injected into Claude Code context via UserPromptSubmit hook
# Runs once per 8 hours, outputs morning brief + last session
BRIEF="$HOME/Desktop/Donut/donut-product/.claude/context/morning-brief.md"
LAST_SESSION="$HOME/Desktop/Donut/donut-product/.claude/context/last-session.md"
BRIEF_GEN="$HOME/Desktop/Donut/Personal/claude-infra/automation/morning-brief.sh"
STAMP_FILE="/tmp/donut-morning-brief-shown"

if [ -f "$STAMP_FILE" ]; then
  last=$(cat "$STAMP_FILE" 2>/dev/null || echo 0)
  now=$(date +%s)
  [ $(( now - last )) -lt 28800 ] && exit 0
fi

if [ ! -f "$BRIEF" ] || [ "$(find "$BRIEF" -mmin +240 2>/dev/null | wc -l | tr -d ' ')" = "1" ]; then
  bash "$BRIEF_GEN" >/dev/null 2>&1 || true
fi

echo "=== MORNING BRIEF (auto-injected) ==="
[ -f "$BRIEF" ] && cat "$BRIEF" || echo "(no brief)"
echo ""
if [ -f "$LAST_SESSION" ]; then
  echo "=== LAST SESSION ==="
  cat "$LAST_SESSION"
fi
echo "=== END CONTEXT ==="
date +%s > "$STAMP_FILE"
HOOKEOF
chmod +x "$HOOK_BIN"
ok "Morning brief hook installed ($HOOK_BIN)"

# Install 8am daily brief generator
BRIEF_GEN_BIN="$HOME/.local/bin/donut-morning-brief-gen"
cat > "$BRIEF_GEN_BIN" << 'GENEOF'
#!/bin/bash
bash "$HOME/Desktop/Donut/Personal/claude-infra/automation/morning-brief.sh"
GENEOF
chmod +x "$BRIEF_GEN_BIN"

MORNING_PLIST="$LAUNCH_AGENTS/com.donut.morning-brief.plist"
cat > "$MORNING_PLIST" << MPLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.donut.morning-brief</string>
    <key>ProgramArguments</key>
    <array>
        <string>$BRIEF_GEN_BIN</string>
    </array>
    <key>StartCalendarInterval</key>
    <dict>
        <key>Hour</key>
        <integer>8</integer>
        <key>Minute</key>
        <integer>0</integer>
    </dict>
    <key>StandardOutPath</key>
    <string>/tmp/donut-morning-brief.log</string>
    <key>StandardErrorPath</key>
    <string>/tmp/donut-morning-brief.log</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>/usr/local/bin:/usr/bin:/bin:/opt/homebrew/bin:$HOME/.bun/bin:$HOME/.local/bin</string>
        <key>HOME</key>
        <string>$HOME</string>
    </dict>
</dict>
</plist>
MPLIST

launchctl unload "$MORNING_PLIST" 2>/dev/null || true
launchctl load "$MORNING_PLIST" 2>/dev/null && ok "Morning brief scheduled daily at 8am" || skip "Morning brief launchd failed"

echo ""

# ─── 2c. Claude Cleanup Daemon ────────────────────────────

echo "2c. Claude Process Cleanup (macOS launchd)"

CLEANUP_BIN="$HOME/.local/bin/donut-claude-cleanup"
cp "$SCRIPT_DIR/claude-cleanup.sh" "$CLEANUP_BIN"
chmod +x "$CLEANUP_BIN"
info "Installed: $CLEANUP_BIN"

CLEANUP_PLIST="$LAUNCH_AGENTS/com.donut.claude-cleanup.plist"
cat > "$CLEANUP_PLIST" << CPLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.donut.claude-cleanup</string>
    <key>ProgramArguments</key>
    <array>
        <string>$CLEANUP_BIN</string>
        <string>--quiet</string>
    </array>
    <key>StartInterval</key>
    <integer>1800</integer>
    <key>RunAtLoad</key>
    <true/>
    <key>StandardOutPath</key>
    <string>/tmp/claude-cleanup.log</string>
    <key>StandardErrorPath</key>
    <string>/tmp/claude-cleanup.log</string>
</dict>
</plist>
CPLIST

launchctl unload "$CLEANUP_PLIST" 2>/dev/null || true
launchctl load "$CLEANUP_PLIST" 2>/dev/null && ok "Claude cleanup daemon installed (every 30min)" || skip "Claude cleanup launchd failed"

echo ""

# ─── 3. Context directories ────────────────────────────────

echo "3. Context & State Setup"

mkdir -p "$REPO_ROOT/.claude/context"
mkdir -p "$REPO_ROOT/.claude/context/session-archive"
mkdir -p "$REPO_ROOT/state"

# Initialize state files if missing
for f in work-in-progress.json completed-tasks.json blocked-items.json; do
  filepath="$REPO_ROOT/state/$f"
  if [ ! -f "$filepath" ]; then
    echo '{"tasks":[],"items":[]}' > "$filepath"
    info "Created $f"
  fi
done

# Ensure session-log.jsonl exists
touch "$REPO_ROOT/state/session-log.jsonl"

# Run initial context generation
if [ -f "$REPO_ROOT/scripts/context-gen/generate-all.sh" ]; then
  bash "$REPO_ROOT/scripts/context-gen/generate-all.sh" 2>/dev/null && ok "Context files generated" || skip "Context generation had issues"
else
  skip "Context generation script not found"
fi

# Generate initial morning brief
bash "$SCRIPT_DIR/morning-brief.sh" >/dev/null 2>&1 && ok "Initial morning brief generated" || skip "Morning brief had issues"

echo ""

# ─── 4. Gitignore check ────────────────────────────────────

echo "4. Gitignore"

GITIGNORE="$REPO_ROOT/.gitignore"
ENTRIES=(".claude/context/" "state/" "/tmp/")

if [ -f "$GITIGNORE" ]; then
  for entry in "${ENTRIES[@]}"; do
    if ! grep -qF "$entry" "$GITIGNORE" 2>/dev/null; then
      echo "$entry" >> "$GITIGNORE"
      info "Added $entry to .gitignore"
    fi
  done
  ok "Gitignore up to date"
else
  printf '%s\n' "${ENTRIES[@]}" > "$GITIGNORE"
  ok "Created .gitignore"
fi

echo ""

# ─── 5. Verify ─────────────────────────────────────────────

echo "5. Verification"

# Check hooks
[ -x "$HOOKS_DIR/pre-push" ] && ok "pre-push hook executable" || skip "pre-push hook not executable"
[ -x "$HOOKS_DIR/post-commit" ] && ok "post-commit hook executable" || skip "post-commit hook not executable"

# Check launchd
launchctl list 2>/dev/null | grep -q "com.donut.token-refresh" && ok "Token refresh daemon running" || skip "Token refresh daemon not running"
launchctl list 2>/dev/null | grep -q "com.donut.claude-cleanup" && ok "Claude cleanup daemon running" || skip "Claude cleanup daemon not running"

# Check context files
[ -f "$REPO_ROOT/.claude/context/morning-brief.md" ] && ok "Morning brief exists" || skip "Morning brief missing"
[ -f "$REPO_ROOT/.claude/context/last-session.md" ] 2>/dev/null && ok "Last session exists" || info "Last session will be created after first commit"

echo ""
echo "═══════════════════════════════════════════════"
echo -e "  ${GREEN}Installation complete!${NC}"
echo ""
echo "  What's now automatic:"
echo "    - Pre-push: deploy validation (secrets, types, lint)"
echo "    - Post-commit: session context saved for next session"
echo "    - Every 15min: token health check (gcloud, gh, Anthropic)"
echo "    - Every 30min: Claude orphaned process cleanup"
echo "    - Session start: morning brief via CLAUDE.md instruction"
echo "    - GitHub PR/push: Linear issue sync + deploy preview"
echo ""
echo "  To deploy GCP health daemon:"
echo "    scp scripts/automation/gcp-health-daemon.sh VM:~/"
echo "    ssh VM 'sudo bash ~/gcp-health-daemon.sh --once'  # test"
echo "    ssh VM 'sudo cp gcp-health.service /etc/systemd/system/'"
echo "    ssh VM 'sudo systemctl enable --now gcp-health.timer'"
echo "═══════════════════════════════════════════════"
